import { FaHome, FaInstagram, FaMusic, FaNewspaper, FaStar, FaUsers, FaChartLine, FaCog } from "react-icons/fa";

export const productivityMessages = [
  "Today contact a producer and ask him for a demo",
  "Send your latest track to 3 new labels",
  "Update your artist bio and social media profiles",
  "Create a new playlist and share it with your network",
  "Reach out to a DJ you admire for collaboration",
  "Practice your DJ skills for at least 2 hours today",
  "Listen to 5 new tracks from artists you don't know",
  "Organize your sample library and delete unused files",
  "Write down 3 new track ideas in your notebook",
  "Connect with 2 new music industry professionals",
  "Review and update your production workflow",
  "Share your music on 3 different platforms today",
  "Study the structure of your favorite tracks",
  "Backup all your projects and samples",
  "Set up a studio session with another producer",
  "Schedule a listening session for new demo submissions.",
  "Reach out to a radio DJ and pitch your latest release.",
  "Update your label's EPK with recent achievements.",
  "Send a thank you note to your top supporters.",
  "Research new DNB artists for potential signings.",
  "Plan a social media campaign for your next release.",
  "Check in with your mastering engineer about upcoming projects.",
  "Organize your release calendar for the next quarter.",
  "Review your label's streaming analytics.",
  "Contact a graphic designer for fresh cover art ideas.",
  "Pitch your latest track to Spotify playlist curators.",
  "Write a press release for your next single.",
  "Connect with a promoter about label showcase events.",
  "Update your label's website with new content.",
  "Send out promo packs to key tastemakers.",
  "Follow up with artists about pending contracts.",
  "Review your label's royalty statements.",
  "Plan a remix contest for your latest release.",
  "Reach out to blogs for coverage of your artists.",
  "Schedule a team meeting to brainstorm new ideas.",
  "Check your label's inbox for demo submissions.",
  "Update your mailing list with new subscribers.",
  "Share a behind-the-scenes video on social media.",
  "Contact a videographer for a music video project.",
  "Review your label's branding and visual identity.",
  "Send out a monthly newsletter to your fans.",
  "Organize a virtual listening party for your next EP.",
  "Reach out to international distributors.",
  "Check in with artists about their upcoming projects.",
  "Plan a merchandise drop for your label.",
  "Update your SoundCloud and Bandcamp profiles.",
  "Research new trends in the DNB scene.",
  "Connect with other label managers for collaboration.",
  "Review your label's financial goals.",
  "Schedule a feedback session with your artists.",
  "Create a content calendar for your social media.",
  "Reach out to a photographer for artist promo shots.",
  "Plan a label takeover on a popular DNB channel.",
  "Update your artist roster on your website.",
  "Send out digital download codes to fans.",
  "Check your label's YouTube analytics.",
  "Organize a Q&A session with your artists.",
  "Plan a charity event or fundraiser.",
  "Review your label's submission guidelines.",
  "Reach out to vinyl pressing plants for quotes.",
  "Update your label's press kit.",
  "Contact a booking agent for tour opportunities.",
  "Plan a collaborative release with another label.",
  "Check in with your PR agency about campaign results.",
  "Celebrate a recent success with your team!",
  "Host a live stream to showcase your label's artists.",
  "Reach out to a podcast for a guest mix opportunity.",
  "Update your artist contracts with the latest terms.",
  "Create a playlist featuring your label's back catalog.",
  "Send a survey to your fans for feedback.",
  "Plan a special release for your label's anniversary.",
  "Check in with your distributor about upcoming releases.",
  "Organize a remix swap between your artists.",
  "Review your label's social media engagement stats.",
  "Contact a music journalist for an interview feature.",
  "Update your label's YouTube channel with new content.",
  "Plan a vinyl reissue of a classic release.",
  "Reach out to a festival about label stage hosting.",
  "Create a press kit for your top artist.",
  "Send a birthday message to an artist on your roster.",
  "Review your label's digital ad campaigns.",
  "Plan a collaborative playlist with another label.",
  "Check your label's sync licensing opportunities.",
  "Organize a feedback session for demo submissions.",
  "Update your label's logo and branding assets.",
  "Reach out to a club for a label night event.",
  "Create a highlight reel of your label's achievements.",
  "Send a thank you package to your top DJs.",
  "Review your label's merchandise sales.",
  "Plan a limited edition release for collectors.",
  "Update your artist bios with recent milestones.",
  "Contact a mastering engineer for a special project.",
  "Organize a listening party for your staff.",
  "Check in with your web developer about site updates.",
  "Plan a social media takeover by one of your artists.",
  "Send out a press release for a charting track.",
  "Review your label's playlist placements.",
  "Reach out to a visual artist for cover collaborations.",
  "Update your label's EPK with new press quotes.",
  "Plan a series of artist interviews for your blog.",
  "Check your label's analytics for top-performing tracks.",
  "Organize a contest for fans to remix a label track.",
  "Send a care package to an artist on tour.",
  "Review your label's YouTube monetization.",
  "Plan a charity compilation with your artists.",
  "Update your label's FAQ for demo submissions.",
  "Contact a PR firm for a new campaign.",
  "Organize a virtual meet-and-greet for fans.",
  "Review your label's international reach.",
  "Plan a series of educational posts for your audience.",
  "Send out a thank you email to your mailing list.",
  "Check in with your accountant about royalties.",
  "Update your label's press contacts list.",
  "Plan a behind-the-scenes documentary.",
  "Celebrate a milestone with a special release party!"
];

export const navigationItems = [
  {
    name: "Dashboard",
    href: "/admin",
    icon: FaHome,
    description: "Overview & Analytics"
  },
  {
    name: "Instagram",
    href: "/admin/instagram",
    icon: FaInstagram,
    description: "Message Management"
  },
  {
    name: "Demo Distribution",
    href: "/admin/demo",
    icon: FaMusic,
    description: "Upload & Send Demos"
  },
  {
    name: "Newsletter",
    href: "/admin/newsletter",
    icon: FaNewspaper,
    description: "Subscriber Management"
  },
  {
    name: "Influencers",
    href: "/admin/influencers",
    icon: FaStar,
    description: "Influencer Database"
  },
  {
    name: "Users",
    href: "/admin/users",
    icon: FaUsers,
    description: "User Management"
  },
  {
    name: "Analytics",
    href: "/admin/analytics",
    icon: FaChartLine,
    description: "Reports & Stats"
  },
  {
    name: "Settings",
    href: "/admin/settings",
    icon: FaCog,
    description: "System Configuration"
  }
];
